'use client'
import { useState, useEffect, useCallback } from 'react'
import { createClient } from '@/lib/supabase/client'
import { TimeLog, KpiRules, Insight } from '@/lib/types'
import { computeKpis } from '@/lib/kpi'
import { Card, PageHeader, Btn, SeverityBadge } from '@/components/ui'
import { useRouter } from 'next/navigation'

export default function InsightsPage() {
  const supabase = createClient()
  const router = useRouter()
  const [insights, setInsights] = useState<Insight[]>([])
  const [selected, setSelected] = useState<Insight|null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const load = useCallback(async () => {
    setLoading(true)
    setError('')
    try {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) return
      const { data: prof } = await supabase.from('profiles').select('name,role').eq('id', user.id).single()
      let q = supabase.from('time_logs').select('*').limit(500)
      if (prof?.role === 'Employee') q = q.eq('user_id', user.id)
      const { data: logs } = await q
      const { data: rulesRaw } = await supabase.from('kpi_rules').select('*').limit(1).single()
      const rules: KpiRules = rulesRaw || { daily_hours_threshold:8, billable_target:70, category_targets:{} }
      const kpis = computeKpis(logs || [])

      const res = await fetch('/api/insights', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ kpis, rules, userName: prof?.name || 'User', role: prof?.role || 'Employee' }),
      })
      const data = await res.json()
      if (data.error) { setError('OpenAI error: ' + data.error); return }
      setInsights(data.insights || [])
    } catch (e: any) {
      setError('Failed to generate insights: ' + e.message)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { load() }, [])

  async function createAction() {
    if (!selected) return
    sessionStorage.setItem('prefill_decision', JSON.stringify({
      type: 'Action',
      title: 'Address: ' + selected.title,
      reason: selected.detail,
      relatedKpi: selected.related,
      linkedInsightId: selected.id,
    }))
    router.push('/dashboard/decisions')
  }

  const sevOrder: Record<string,number> = { High:0, Med:1, Low:2 }
  const sorted = [...insights].sort((a,b) => (sevOrder[a.severity]||2) - (sevOrder[b.severity]||2))

  return (
    <div>
      <PageHeader title="AI Insights" subtitle="Real-time insights generated by GPT-4o-mini from your activity data."
        action={<Btn primary onClick={load} disabled={loading}>{loading ? 'Generating...' : 'Regenerate Insights'}</Btn>} />

      {loading && (
        <div style={{ textAlign:'center', padding:48, color:'#6b6860', fontSize:13 }}>
          <div style={{ marginBottom:8 }}>Analysing your data with GPT-4o-mini...</div>
          <div style={{ fontSize:11, color:'#9e9b94' }}>This takes a few seconds</div>
        </div>
      )}

      {error && (
        <div style={{ background:'#fdecea', border:'1px solid #f5c6cb', borderRadius:8, padding:16, marginBottom:20, fontSize:13, color:'#c0392b' }}>
          {error}
          <div style={{ marginTop:8, fontSize:12, color:'#9e9b94' }}>Make sure your OPENAI_API_KEY is set in .env.local and you have API credits.</div>
        </div>
      )}

      {!loading && !error && sorted.length === 0 && (
        <Card><div style={{ textAlign:'center', padding:32, color:'#9e9b94', fontSize:13 }}>Click Regenerate Insights to analyse your data.</div></Card>
      )}

      {!loading && sorted.length > 0 && (
        <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fill,minmax(300px,1fr))', gap:16 }}>
          {sorted.map(ins => (
            <div key={ins.id} onClick={() => setSelected(selected?.id===ins.id ? null : ins)}
              style={{ background:'#fff', border:'1px solid ' + (selected?.id===ins.id ? '#2a5cff' : '#e2e0d8'),
                borderRadius:8, padding:16, cursor:'pointer',
                boxShadow: selected?.id===ins.id ? '0 0 0 2px #eef1ff' : '0 1px 3px rgba(0,0,0,0.08)' }}>
              <div style={{ marginBottom:8 }}><SeverityBadge severity={ins.severity} /></div>
              <div style={{ fontWeight:600, fontSize:14, marginBottom:6 }}>{ins.title}</div>
              <div style={{ fontSize:13, color:'#6b6860', lineHeight:1.5 }}>
                {ins.detail.slice(0,140)}{ins.detail.length>140 ? '...' : ''}
              </div>
              <div style={{ marginTop:10, fontSize:11, color:'#9e9b94' }}>Related: {ins.related}</div>
            </div>
          ))}
        </div>
      )}

      {selected && (
        <Card style={{ marginTop:20, borderColor:'#2a5cff' }}>
          <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:12 }}>
            <div>
              <SeverityBadge severity={selected.severity} />
              <div style={{ fontWeight:600, fontSize:16, marginTop:8 }}>{selected.title}</div>
            </div>
            <Btn onClick={() => setSelected(null)}>Close</Btn>
          </div>
          <p style={{ fontSize:13, color:'#6b6860', lineHeight:1.6, marginBottom:12 }}>{selected.detail}</p>
          <div style={{ fontSize:12, color:'#9e9b94', marginBottom:16 }}>Severity: {selected.severity} | Related: {selected.related}</div>
          <Btn primary onClick={createAction}>Create Action from This Insight</Btn>
        </Card>
      )}
    </div>
  )
}
